### ISSUE TITLE
multiselect two sides with none style

### ISSUE THREAD

**Issue by frankrod** [VovanR/react-multiselect-two-sides#21]
Hi. It looks like the component is not getting styles at all. 
This is how it looks right now:
![screen shot 2018-01-30 at 9 08 40 am](https://user-images.githubusercontent.com/5304641/35573763-977a6650-059d-11e8-9bc9-767a070033c1.png)

**Comment by VovanR** [comment]
Component unstyled by default.
You can use `styles.css` that distributed with package. Or styles from example `example/styles.css`. I can add builded example theme to package if you need it.

**Comment by frankrod** [comment]
oh, I see. Thanks for the clarification!
