### ISSUE TITLE
Build Issue while bundling the react-multiselect-two-sides component in create-react-app

### ISSUE THREAD

**Issue by vmengh** [VovanR/react-multiselect-two-sides#24]
Hi, 
We need to use this component in one of the react projects. After following the steps in the git repo we could install the component and bring it to the page through npm install. it all works fine during the application local development.

But when we try to create a minified build file of the project using npm run-script build, it throws an error as below
**Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:
        ./node_modules/react-multiselect-two-sides/lib/index.js:78**

So it doesn't generate a normal build. by going through the details of log and possible work around using this link
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

We uninstalled the component and included all the component files under the src/components folder of the project  and updated relevant references in JS files. 
After including the component files in the project the Build works fine and I am able to deploy the project.

Can you please suggest if I am missing something here or can you publish the package pre-compiled?

Note  - We are using react 16.3.2 on create-react-app boilerplate app and Tomcat for deployment.

Kindly Suggest.

Thanks & Regards,
Vmengh

**Comment by VovanR** [comment]
@vmengh Fixed with 0.13.2

**Comment by vmengh** [comment]
Hi Vovan,

Thanks for a quick response on this. It's really helpful. I just tested the build with v0.13.2 and it works fine.
Thanks a lot. Appreciate quick turn around.

Regards,
vmengh
