### ISSUE TITLE
Select All filtered options

### ISSUE THREAD

**Issue by Jsimon44** [VovanR/react-multiselect-two-sides#31]
Is it possible to pass over only the filtered options from the available side to the selected side using the select all button. 
My current behavior is I have 18 options that display on the available side and I filter down to display only 3, however when I click the select all button, all 18 option move into the selected field. 
How can I modify this behavior to only move the filtered options to the selected side?

**Comment by VovanR** [comment]
@Jsimon44 done! Update to v0.16.0
